# Generated by Django 2.2.6 on 2020-06-28 05:58

import core.helpers
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalTraining',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('title', models.CharField(default='NA', max_length=100)),
                ('description', models.CharField(default='NA', max_length=100)),
                ('organiser_type', models.CharField(choices=[('LL', 'Luaran'), ('DD', 'Dalaman'), ('OT', 'Lain-Lain')], default='OT', max_length=2)),
                ('course_type', models.CharField(choices=[('KK', 'Kursus'), ('PP', 'Persidangan'), ('SS', 'Seminar'), ('BB', 'Bengkel'), ('LK', 'Lawatan Kerja'), ('TT', 'Taklimat'), ('SP', 'Sesi Perjumpaan'), ('OT', 'Lain-Lain')], default='OT', max_length=2)),
                ('category', models.CharField(default='-', max_length=100)),
                ('course_code', models.CharField(default='NA', max_length=100)),
                ('target_group_type', models.CharField(choices=[('TB', 'Terbuka'), ('TH', 'Terhad')], default='TB', max_length=2)),
                ('target_group', models.CharField(choices=[('GD', 'Gred'), ('JB', 'Jabatan'), ('JW', 'Jawatan'), ('SM', 'Semua'), ('SP', 'Skim Perkhidmatan')], default='SM', max_length=2)),
                ('department', models.CharField(choices=[('KA', 'Kawalan Bangunan'), ('KN', 'Kejuruteraan'), ('KK', 'Kesihatan, Persekitaraan dan Pelesenan'), ('PB', 'Perbendaharaan'), ('PP', 'Penilaian dan Pengurusan Harta'), ('UU', 'Undang-undang'), ('KP', 'Khidmat Pengurusan'), ('KM', 'Khidmat Kemasyarakatan'), ('KW', 'Konservasi Warisan'), ('PB', 'Pesuruhjaya Bangunan'), ('PG', 'Penguatkuasaan'), ('PN', 'Perkhidmatan Perbandaran'), ('LL', 'Landskap'), ('BP', 'Bahagian Pelesenan'), ('UD', 'Unit Audit Dalaman'), ('UO', 'Unit OSC'), ('OT', 'Other')], default='OT', max_length=2)),
                ('max_participant', models.IntegerField(default=0)),
                ('venue', models.CharField(default='NA', max_length=50, null=True)),
                ('address', models.CharField(default='NA', max_length=50, null=True)),
                ('start_date', models.DateField(null=True)),
                ('start_time', models.TimeField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('end_time', models.TimeField(null=True)),
                ('cost', models.IntegerField(default=0)),
                ('duration_days', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('DB', 'Dibuka'), ('DT', 'Ditutup'), ('PN', 'Penuh'), ('TN', 'Tangguh'), ('OT', 'Lain-lain')], default='OT', max_length=2)),
                ('fasilitator', models.CharField(blank=True, default='NA', max_length=100, null=True)),
                ('attachment', models.TextField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical training',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(default='NA', max_length=100)),
                ('description', models.CharField(default='NA', max_length=100)),
                ('organiser_type', models.CharField(choices=[('LL', 'Luaran'), ('DD', 'Dalaman'), ('OT', 'Lain-Lain')], default='OT', max_length=2)),
                ('course_type', models.CharField(choices=[('KK', 'Kursus'), ('PP', 'Persidangan'), ('SS', 'Seminar'), ('BB', 'Bengkel'), ('LK', 'Lawatan Kerja'), ('TT', 'Taklimat'), ('SP', 'Sesi Perjumpaan'), ('OT', 'Lain-Lain')], default='OT', max_length=2)),
                ('category', models.CharField(default='-', max_length=100)),
                ('course_code', models.CharField(default='NA', max_length=100)),
                ('target_group_type', models.CharField(choices=[('TB', 'Terbuka'), ('TH', 'Terhad')], default='TB', max_length=2)),
                ('target_group', models.CharField(choices=[('GD', 'Gred'), ('JB', 'Jabatan'), ('JW', 'Jawatan'), ('SM', 'Semua'), ('SP', 'Skim Perkhidmatan')], default='SM', max_length=2)),
                ('department', models.CharField(choices=[('KA', 'Kawalan Bangunan'), ('KN', 'Kejuruteraan'), ('KK', 'Kesihatan, Persekitaraan dan Pelesenan'), ('PB', 'Perbendaharaan'), ('PP', 'Penilaian dan Pengurusan Harta'), ('UU', 'Undang-undang'), ('KP', 'Khidmat Pengurusan'), ('KM', 'Khidmat Kemasyarakatan'), ('KW', 'Konservasi Warisan'), ('PB', 'Pesuruhjaya Bangunan'), ('PG', 'Penguatkuasaan'), ('PN', 'Perkhidmatan Perbandaran'), ('LL', 'Landskap'), ('BP', 'Bahagian Pelesenan'), ('UD', 'Unit Audit Dalaman'), ('UO', 'Unit OSC'), ('OT', 'Other')], default='OT', max_length=2)),
                ('max_participant', models.IntegerField(default=0)),
                ('venue', models.CharField(default='NA', max_length=50, null=True)),
                ('address', models.CharField(default='NA', max_length=50, null=True)),
                ('start_date', models.DateField(null=True)),
                ('start_time', models.TimeField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('end_time', models.TimeField(null=True)),
                ('cost', models.IntegerField(default=0)),
                ('duration_days', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('DB', 'Dibuka'), ('DT', 'Ditutup'), ('PN', 'Penuh'), ('TN', 'Tangguh'), ('OT', 'Lain-lain')], default='OT', max_length=2)),
                ('fasilitator', models.CharField(blank=True, default='NA', max_length=100, null=True)),
                ('attachment', models.FileField(null=True, upload_to=core.helpers.PathAndRename('attachments'))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingAbsenceMemo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingAttendee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('is_attend', models.BooleanField(default=False)),
                ('check_in', models.DateTimeField(null=True)),
                ('check_out', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('code', models.CharField(default='NA', max_length=70, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(default='NA', max_length=50)),
                ('note_code', models.CharField(default='NA', max_length=10)),
                ('note_file', models.FileField(null=True, upload_to=core.helpers.PathAndRename('notes'))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('training', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trainings.Training')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
