# Generated by Django 2.2.6 on 2020-06-28 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0001_initial'),
        ('trainings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingattendee',
            name='attendee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingattendee',
            name='training',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trainings.Training'),
        ),
        migrations.AddField(
            model_name='trainingattendee',
            name='verified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendee_verified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingabsencememo',
            name='attendee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='absence_attendee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingabsencememo',
            name='training',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='absence_training', to='trainings.Training'),
        ),
        migrations.AddField(
            model_name='training',
            name='organiser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_organiser', to='organisations.Organisation'),
        ),
        migrations.AddField(
            model_name='training',
            name='speaker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_speaker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaltraining',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaltraining',
            name='organiser',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organisations.Organisation'),
        ),
        migrations.AddField(
            model_name='historicaltraining',
            name='speaker',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
