# Generated by Django 2.2.6 on 2020-06-29 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trainings', '0002_auto_20200628_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltraining',
            name='course_type',
            field=models.CharField(choices=[('BB', 'Bengkel'), ('KK', 'Kursus'), ('LK', 'Lawatan Kerja'), ('PP', 'Persidangan'), ('SP', 'Sesi Perjumpaan'), ('SS', 'Seminar'), ('TT', 'Taklimat'), ('OT', 'Lain-Lain')], default='OT', max_length=2),
        ),
        migrations.AlterField(
            model_name='historicaltraining',
            name='department',
            field=models.CharField(choices=[('KA', 'Kawalan Bangunan'), ('KN', 'Kejuruteraan'), ('KK', 'Kesihatan, Persekitaraan dan Pelesenan'), ('PB', 'Perbendaharaan'), ('PP', 'Penilaian dan Pengurusan Harta'), ('UU', 'Undang-undang'), ('KP', 'Khidmat Pengurusan'), ('KM', 'Khidmat Kemasyarakatan'), ('KW', 'Konservasi Warisan'), ('PB', 'Pesuruhjaya Bangunan'), ('PG', 'Penguatkuasaan'), ('PN', 'Perkhidmatan Perbandaran'), ('LL', 'Landskap'), ('BP', 'Bahagian Pelesenan'), ('UD', 'Unit Audit Dalaman'), ('UO', 'Unit OSC'), ('SM', 'Semua')], default='SM', max_length=2),
        ),
        migrations.AlterField(
            model_name='historicaltraining',
            name='target_group',
            field=models.CharField(choices=[('KA', 'Kumpulan A'), ('KB', 'Kumpulan B'), ('KC', 'Kumpulan C'), ('KD', 'Kumpulan D'), ('SM', 'Semua')], default='SM', max_length=2),
        ),
        migrations.AlterField(
            model_name='training',
            name='course_type',
            field=models.CharField(choices=[('BB', 'Bengkel'), ('KK', 'Kursus'), ('LK', 'Lawatan Kerja'), ('PP', 'Persidangan'), ('SP', 'Sesi Perjumpaan'), ('SS', 'Seminar'), ('TT', 'Taklimat'), ('OT', 'Lain-Lain')], default='OT', max_length=2),
        ),
        migrations.AlterField(
            model_name='training',
            name='department',
            field=models.CharField(choices=[('KA', 'Kawalan Bangunan'), ('KN', 'Kejuruteraan'), ('KK', 'Kesihatan, Persekitaraan dan Pelesenan'), ('PB', 'Perbendaharaan'), ('PP', 'Penilaian dan Pengurusan Harta'), ('UU', 'Undang-undang'), ('KP', 'Khidmat Pengurusan'), ('KM', 'Khidmat Kemasyarakatan'), ('KW', 'Konservasi Warisan'), ('PB', 'Pesuruhjaya Bangunan'), ('PG', 'Penguatkuasaan'), ('PN', 'Perkhidmatan Perbandaran'), ('LL', 'Landskap'), ('BP', 'Bahagian Pelesenan'), ('UD', 'Unit Audit Dalaman'), ('UO', 'Unit OSC'), ('SM', 'Semua')], default='SM', max_length=2),
        ),
        migrations.AlterField(
            model_name='training',
            name='target_group',
            field=models.CharField(choices=[('KA', 'Kumpulan A'), ('KB', 'Kumpulan B'), ('KC', 'Kumpulan C'), ('KD', 'Kumpulan D'), ('SM', 'Semua')], default='SM', max_length=2),
        ),
        migrations.CreateModel(
            name='TrainingApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('application_type', models.CharField(choices=[('PS', 'Permohonan Persendirian'), ('PP', 'Permohonan Pencalonan')], default='PS', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('applicant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_attendee', to=settings.AUTH_USER_MODEL)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_verified_by', to=settings.AUTH_USER_MODEL)),
                ('training', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trainings.Training')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
