# Generated by Django 2.2.6 on 2020-06-29 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0003_auto_20200629_0821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltraining',
            name='category',
        ),
        migrations.RemoveField(
            model_name='training',
            name='category',
        ),
    ]
