# Generated by Django 2.2.6 on 2020-06-29 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trainings', '0004_auto_20200629_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingabsencememo',
            name='verified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='absence_verified_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
