# Generated by Django 2.2.6 on 2020-07-01 09:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0006_auto_20200630_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltraining',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='training',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='trainingabsencememo',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='trainingapplication',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='trainingattendee',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='trainingcode',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='trainingnote',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='historicaltraining',
            name='modified_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='training',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='trainingabsencememo',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='trainingapplication',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='trainingattendee',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='trainingcode',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='trainingnote',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
