# Generated by Django 2.2.6 on 2020-07-02 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0008_auto_20200702_0301'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltraining',
            name='transportation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='training',
            name='transportation',
            field=models.BooleanField(default=False),
        ),
    ]
