# Generated by Django 2.2.6 on 2020-09-08 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0009_auto_20200702_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltraining',
            name='course_type',
            field=models.CharField(choices=[('BB', 'Bengkel'), ('KK', 'Kursus'), ('LK', 'Lawatan Kerja'), ('LT', 'Latihan'), ('PG', 'Program'), ('PP', 'Persidangan'), ('SB', 'Sambutan'), ('SP', 'Sesi Perjumpaan'), ('SS', 'Seminar'), ('TT', 'Taklimat')], default='OT', max_length=2),
        ),
        migrations.AlterField(
            model_name='training',
            name='course_type',
            field=models.CharField(choices=[('BB', 'Bengkel'), ('KK', 'Kursus'), ('LK', 'Lawatan Kerja'), ('LT', 'Latihan'), ('PG', 'Program'), ('PP', 'Persidangan'), ('SB', 'Sambutan'), ('SP', 'Sesi Perjumpaan'), ('SS', 'Seminar'), ('TT', 'Taklimat')], default='OT', max_length=2),
        ),
    ]
