# Generated by Django 2.2.6 on 2021-01-14 21:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0010_auto_20200908_0320'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingCore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('parent', models.CharField(choices=[('FN', 'Fungsional'), ('GN', 'Generik')], default='GN', max_length=2)),
                ('child', models.CharField(default='NA', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='trainingnote',
            name='training',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_training_notes', to='trainings.Training'),
        ),
        migrations.AddField(
            model_name='historicaltraining',
            name='core',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='trainings.TrainingCore'),
        ),
        migrations.AddField(
            model_name='training',
            name='core',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_traininc_core', to='trainings.TrainingCore'),
        ),
    ]
