# Generated by Django 2.2.6 on 2021-01-15 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0012_auto_20210114_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltraining',
            name='facilitator',
        ),
        migrations.RemoveField(
            model_name='historicaltraining',
            name='speaker',
        ),
        migrations.RemoveField(
            model_name='training',
            name='facilitator',
        ),
        migrations.RemoveField(
            model_name='training',
            name='speaker',
        ),
        migrations.AlterField(
            model_name='trainingabsencememo',
            name='attendee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_absence_memo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trainingapplication',
            name='training',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_application', to='trainings.Training'),
        ),
        migrations.AlterField(
            model_name='trainingattendee',
            name='training',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_attendee', to='trainings.Training'),
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('trainer_type', models.CharField(choices=[('FC', 'Facilitator'), ('SP', 'Speaker')], default='FC', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('training', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainer_training', to='trainings.Training')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
