# Generated by Django 2.2.6 on 2021-01-15 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0013_auto_20210115_1404'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrainingCode',
        ),
        migrations.AlterField(
            model_name='historicaltraining',
            name='course_code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='course_code',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
