# Generated by Django 2.2.6 on 2021-01-15 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0014_auto_20210115_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltraining',
            name='duration_days',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='duration_days',
            field=models.IntegerField(null=True),
        ),
    ]
