# Generated by Django 2.2.6 on 2021-01-16 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trainings', '0015_auto_20210115_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltraining',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'user_type': 'TC'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='training',
            name='created_by',
            field=models.ForeignKey(limit_choices_to={'user_type': 'TC'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
