# Generated by Django 2.2.6 on 2021-01-17 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0016_auto_20210116_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltraining',
            name='status',
            field=models.CharField(choices=[('DB', 'Dibuka'), ('DT', 'Ditutup'), ('PN', 'Penuh'), ('TN', 'Tangguh'), ('SL', 'Selesai'), ('OT', 'Lain-lain')], default='DB', max_length=2),
        ),
        migrations.AlterField(
            model_name='training',
            name='status',
            field=models.CharField(choices=[('DB', 'Dibuka'), ('DT', 'Ditutup'), ('PN', 'Penuh'), ('TN', 'Tangguh'), ('SL', 'Selesai'), ('OT', 'Lain-lain')], default='DB', max_length=2),
        ),
    ]
