# Generated by Django 2.2.6 on 2021-01-18 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0018_trainingdomain'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltraining',
            name='domain',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='trainings.TrainingDomain'),
        ),
        migrations.AddField(
            model_name='training',
            name='domain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_domain', to='trainings.TrainingDomain'),
        ),
    ]
