# Generated by Django 2.2.6 on 2021-01-19 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0019_auto_20210118_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingdomain',
            name='shortname',
        ),
    ]
