# Generated by Django 2.2.6 on 2021-01-22 03:26

import core.helpers
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0020_remove_trainingdomain_shortname'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltraining',
            name='attachment_approval',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='attachment_approval',
            field=models.FileField(null=True, upload_to=core.helpers.PathAndRename('attachments')),
        ),
        migrations.CreateModel(
            name='TrainingQuota',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('training', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_quota', to='trainings.Training')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
