# Generated by Django 2.2.6 on 2021-01-25 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0024_auto_20210124_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingabsencememo',
            name='attendee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='absence_attendee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trainingabsencememo',
            name='training',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_absence_memo', to='trainings.Training'),
        ),
    ]
