# Generated by Django 2.2.6 on 2021-01-26 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0026_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
