# Generated by Django 2.2.6 on 2021-02-01 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0031_auto_20210130_0856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingapplication',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='trainingapplication',
            name='status',
            field=models.CharField(choices=[('AP', 'Diterima'), ('RJ', 'Ditolak'), ('RS', 'Disimpan'), ('IP', 'Dalam proses')], default='IP', max_length=2),
        ),
    ]
