# Generated by Django 2.2.6 on 2021-02-07 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trainings', '0032_auto_20210201_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingapplication',
            name='approved_by',
        ),
        migrations.AddField(
            model_name='trainingapplication',
            name='approved_level_3_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_approved_level_3_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
