# Generated by Django 2.2.6 on 2021-02-07 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trainings', '0033_auto_20210207_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingapplication',
            name='approved_level_1_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_approved_level_1_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingapplication',
            name='approved_level_2_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_approved_level_2_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
