# Generated by Django 2.2.6 on 2021-02-07 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trainings', '0034_auto_20210207_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingattendee',
            name='checked_in_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendee_checked_in_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingattendee',
            name='checked_out_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendee_checked_out_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
