# Generated by Django 2.2.6 on 2021-02-08 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0035_auto_20210207_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingnote',
            name='note_code',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
