# Generated by Django 2.2.6 on 2021-02-08 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0036_auto_20210209_0459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingnote',
            name='note_code',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
