# Generated by Django 2.2.6 on 2021-02-27 07:38

import core.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0038_trainingabsencememo_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='attachment',
            field=models.FileField(null=True, upload_to=core.helpers.PathAndRename('mbpp-elatihan/attachments')),
        ),
        migrations.AlterField(
            model_name='training',
            name='attachment_approval',
            field=models.FileField(null=True, upload_to=core.helpers.PathAndRename('mbpp-elatihan/attachments')),
        ),
        migrations.AlterField(
            model_name='trainingabsencememo',
            name='attachment',
            field=models.FileField(null=True, upload_to=core.helpers.PathAndRename('mbpp-elatihan/attachments')),
        ),
        migrations.AlterField(
            model_name='trainingnote',
            name='note_file',
            field=models.FileField(null=True, upload_to=core.helpers.PathAndRename('mbpp-elatihan/notes')),
        ),
    ]
