# Generated by Django 2.2.6 on 2021-03-22 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0040_basiclevel_monitoringplan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monitoringplan',
            options={'ordering': ['-year']},
        ),
    ]
