# Generated by Django 2.2.6 on 2021-08-04 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0041_auto_20210322_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingattendee',
            name='check_date',
            field=models.DateField(null=True),
        ),
    ]
