# Generated by Django 2.0.5 on 2020-02-28 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0002_auto_20200224_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='client_type',
        ),
    ]
