apiVersion: apps/v1
kind: Deployment
metadata:
  name: mbpp-elatihan-api-celery-beat
  labels:
    deployment: mbpp-elatihan-api-celery-beat
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: mbpp-elatihan-api-celery-beat
  template:
    metadata:
      labels:
        pod: mbpp-elatihan-api-celery-beat
    spec:
      containers:
        - name: mbpp-elatihan-api-celery-beat
          image: syafiqpipe/mbpp-elatihan-api
          # celery -A mbpp-elatihanapi beat -l debug
          command: ['celery', '-A', 'core', 'beat', '-l', 'debug']
          envFrom:
            - secretRef:
                name: mbpp-elatihan-api-secret   