export const UserType = [
    { value: 'AD', text: 'PENTADBIR SISTEM' },
    { value: 'DC', text: 'PENYELARAS JABATAN' },
    { value: 'DH', text: 'KETUA JABATAN' },
    { value: 'ST', text: 'KAKITANGAN' },
    { value: 'TC', text: 'PENYELARAS LATIHAN' }
]

export const ServiceStatus = [
    { value: 'K', text: 'KONTRAK' },
    { value: 'S', text: 'SEMENTARA' },
    { value: 'T', text: 'TETAP' }
]

export const Department = [
    { value: '11', text: 'JABATAN KHIDMAT PENGURUSAN' },
    { value: '15', text: 'JABATAN PENGUATKUASAAN' },
    { value: '21', text: 'JABATAN PERBENDAHARAAN' },
    { value: '31', text: 'JABATAN KEJURUTERAAN' },
    { value: '41', text: 'JABATAN KESIHATAN PERSEKITARAN DAN PELESENAN' },
    { value: '45', text: 'JABATAN PERKHIDMATAN DAN PERBANDARAAN' },
    { value: '47', text: 'JABATAN KESIHATAN PERSEKITARAN DAN PELESENAN - PELESENAN' },
    { value: '51', text: 'JABATAN KAWALAN BANGUNAN' },
    { value: '55', text: 'JABATAN KONSERVASI WARISAN' },
    { value: '61', text: 'JABATAN PENILAIAN DAN PENGURUSAN HARTA' },
    { value: '63', text: 'JABATAN PESURUHJAYA BANGUNAN' },
    { value: '71', text: 'JABATAN PERANCANGAN PEMBANGUNAN' },
    { value: '81', text: 'JABATAN KHIDMAT KEMASYARAKATAN' },
    { value: '86', text: 'JABATAN LANDSKAP' },
    { value: '90', text: 'PEJABAT DATUK BANDAR' },
    { value: '91', text: 'PEJABAT DATUK BANDAR - UNDANG - UNDANG' },
    { value: '92', text: 'PEJABAT DATUK BANDAR - PENYELARASAN PEMBANGUNAN' },
    { value: '93', text: 'PEJABAT DATUK BANDAR - AUDIT DALAM' },
    { value: '94', text: 'PEJABAT DATUK BANDAR - OSC' }
]

export const Section = [
    { value: '111', text: 'JABATAN KHIDMAT PENGURUSAN' },
    { value: '11A', text: 'JABATAN KHIDMAT PENGURUSAN - PENTADBIRAN DAN KEURUSETIAAN' },
    { value: '11B', text: 'JABATAN KHIDMAT PENGURUSAN - PENGURUSAN MODAL INSAN' },
    { value: '11C', text: 'JABATAN KHIDMAT PENGURUSAN - KOMUNIKASI KORPORAT DAN PERHUBUNGAN AWAM' },
    { value: '11D', text: 'JABATAN KHIDMAT PENGURUSAN - TEKNOLOGI MAKLUMAT' },
    { value: '11E', text: 'JABATAN KHIDMAT PENGURUSAN - KESELAMATAN' },
    { value: '115', text: 'JABATAN PENGUATKUASAAN' },
    { value: '221', text: 'JABATAN PERBENDAHARAAN' },
    { value: '21A', text: 'JABATAN PERBENDAHARAAN - AKAUN DAN HASIL' },
    { value: '21B', text: 'JABATAN PERBENDAHARAAN - KAWANGAN DAN BELANJAWAN' },
    { value: '21C', text: 'JABATAN PERBENDAHARAAN - LETAK KERETA' },
    { value: '331', text: 'JABATAN KEJURUTERAAN' },
    { value: '31A', text: 'JABATAN KEJURUTERAAN - LALULINTAS DAN PENGANGKUTAN AWAM' },
    { value: '31B', text: 'JABATAN KEJURUTERAAN - MEKANIKAL DAN ELEKTRIKAL' },
    { value: '31C', text: 'JABATAN KEJURUTERAAN - PENYELENGGARAAN' },
    { value: '31D', text: 'JABATAN KEJURUTERAAN - GEOTEKNIKAL' },
    { value: '31E', text: 'JABATAN KEJURUTERAAN - PENTADBIRAN' },
    { value: '441', text: 'BAHAGIAN KESIHATAN AWAM' },
    { value: '410', text: 'JABATAN KESIHATAN PERSEKITARAN DAN PELESENAN' },
    { value: '41A', text: 'BAHAGIAN KESIHATAN AWAM - PERKHIDMATAN VETERINAR' },
    { value: '41B', text: 'BAHAGIAN KESIHATAN AWAM - KESIHATAN AWAM' },
    { value: '41C', text: 'BAHAGIAN KESIHATAN AWAM - KLINIK' },
    { value: '41D', text: 'BAHAGIAN KESIHATAN AWAM - PENTADBIRAN' },
    { value: '445', text: 'JABATAN PERKHIDMATAN PERBANDARAN' },
    { value: '45A', text: 'JABATAN PERKHIDMATAN PERBANDARAN - PERKHIDMATAN PERBANDARAN (PEMBERSIHAN)' },
    { value: '45B', text: 'JABATAN PERKHIDMATAN PERBANDARAN - ZON PERINDUSTRIAN DAN PASAR-PASAR' },
    { value: '45C', text: 'JABATAN PERKHIDMATAN PERBANDARAN - PENTADBIRAN' },
    { value: '447', text: 'BAHAGIAN PELESENAN' },
    { value: '47A', text: 'BAHAGIAN PELESENAN - PELESENAN' },
    { value: '47B', text: 'BAHAGIAN PELESENAN - PERNIAGAAN KECIL' },
    { value: '47C', text: 'BAHAGIAN PELESENAN - TRED PERNIAGAAN INDUSTRI DAN MAKANAN' },
    { value: '551', text: 'JABATAN KAWALAN BANGUNAN' },
    { value: '51A', text: 'JABATAN KAWALAN BANGUNAN - SENIBINA DAN KEMAJUAN' },
    { value: '51B', text: 'JABATAN KAWALAN BANGUNAN - KAWALAN BANGUNAN' },
    { value: '51C', text: 'JABATAN KAWALAN BANGUNAN - PENTADBIRAN' },
    { value: '555', text: 'JABATAN KONSERVASI WARISAN' },
    { value: '55A', text: 'JABATAN KONSERVASI WARISAN - PENYELIDIKAN DAN PEMBANGUNAN (RnD)' },
    { value: '661', text: 'JABATAN PENILAIAN DAN PENGURUSAN HARTA' },
    { value: '61A', text: 'JABATAN PENILAIAN DAN PENGURUSAN HARTA - PENTADBIRAN' },
    { value: '61B', text: 'JABATAN PENILAIAN DAN PENGURUSAN HARTA - PENILAIAN' },
    { value: '61C', text: 'JABATAN PENILAIAN DAN PENGURUSAN HARTA - PENGURUSAN HARTA' },
    { value: '663', text: 'BAHAGIAN PESURUHJAYA BANGUNAN' },
    { value: '771', text: 'JABATAN PERANCANGAN PEMBANGUNAN' },
    { value: '71A', text: 'JABATAN PERANCANGAN PEMBANGUNAN - PERANCANGAN PEMAJUAN' },
    { value: '71B', text: 'JABATAN PERANCANGAN PEMBANGUNAN - KAWALAN PEMAJUAN' },
    { value: '71C', text: 'JABATAN PERANCANGAN PEMBANGUNAN - PENYELIDIKAN PROJEK/GIS' },
    { value: '71D', text: 'JABATAN PERANCANGAN PEMBANGUNAN - PENTADBIRAN' },
    { value: '881', text: 'JABATAN KHIDMAT KEMASYARAKATAN' },
    { value: '81A', text: 'JABATAN KHIDMAT KEMASYARAKATAN - PERINDUSTRIAN DAN REKREASI' },
    { value: '81B', text: 'JABATAN KHIDMAT KEMASYARAKATAN - SUKAN, KEBUDAYAAN & PELANCONGAN' },
    { value: '886', text: 'JABATAN LANDSKAP' },
    { value: '990', text: 'PEJABAT DATUK BANDAR' },
    { value: '991', text: 'UNIT UNDANG-UNDANG' },
    { value: '91A', text: 'UNIT UNDANG-UNDANG - PENDAKWAAN' },
    { value: '91B', text: 'UNIT UNDANG-UNDANG - SIVIL' },
    { value: '91C', text: 'UNIT UNDANG-UNDANG - PENTADBIRAN' },
    { value: '91D', text: 'UNIT UNDANG-UNDANG - LEMBAGA RAYUAN DAN KONTRAK' },
    { value: '992', text: 'UNIT PENYELARASAN PEMBANGUNAN' },
    { value: '993', text: 'UNIT AUDIT DALAM' },
    { value: '994', text: 'UNIT PUSAT SEHENTI (OSC)' }
]
