# Generated by Django 2.2.6 on 2020-06-28 05:58

import core.helpers
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0001_initial'),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(blank=True, max_length=100)),
                ('staff_id', models.CharField(blank=True, max_length=100)),
                ('nric', models.CharField(blank=True, max_length=12)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('mobile', models.CharField(blank=True, max_length=12)),
                ('gender', models.CharField(choices=[('ML', 'Male'), ('FM', 'Female'), ('NA', 'Not Available')], default='NA', max_length=2)),
                ('user_type', models.CharField(choices=[('ST', 'Staff'), ('DC', 'Department Coordinator'), ('TC', 'Training Coordinator'), ('AD', 'Administrator'), ('TR', 'Trainer')], default='ST', max_length=2)),
                ('grade', models.CharField(blank=True, max_length=100)),
                ('position', models.CharField(blank=True, max_length=100)),
                ('salary_code', models.CharField(blank=True, max_length=100)),
                ('department', models.CharField(choices=[('KA', 'Kawalan Bangunan'), ('KN', 'Kejuruteraan'), ('KK', 'Kesihatan, Persekitaraan dan Pelesenan'), ('PB', 'Perbendaharaan'), ('PP', 'Penilaian dan Pengurusan Harta'), ('UU', 'Undang-undang'), ('KP', 'Khidmat Pengurusan'), ('KM', 'Khidmat Kemasyarakatan'), ('KW', 'Konservasi Warisan'), ('PB', 'Pesuruhjaya Bangunan'), ('PG', 'Penguatkuasaan'), ('PN', 'Perkhidmatan Perbandaran'), ('LL', 'Landskap'), ('BP', 'Bahagian Pelesenan'), ('UD', 'Unit Audit Dalaman'), ('UO', 'Unit OSC'), ('NA', 'Not Available')], default='OT', max_length=2)),
                ('marital_type', models.CharField(choices=[('BW', 'Berkahwin'), ('BJ', 'Bujang'), ('NA', 'Not Available')], default='NA', max_length=2)),
                ('religion', models.CharField(choices=[('IM', 'Islam'), ('BA', 'Buddha'), ('HN', 'Hindu'), ('KN', 'Kristian'), ('NA', 'Not Available')], default='NA', max_length=2)),
                ('race', models.CharField(choices=[('MU', 'Melayu'), ('ID', 'India'), ('CN', 'Cina'), ('NA', 'Not Available')], default='OT', max_length=2)),
                ('profile_picture', models.ImageField(null=True, upload_to=core.helpers.PathAndRename('images'))),
                ('is_first_login', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('organisation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organisations.Organisation')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['-full_name'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalCustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(db_index=True, error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('full_name', models.CharField(blank=True, max_length=100)),
                ('staff_id', models.CharField(blank=True, max_length=100)),
                ('nric', models.CharField(blank=True, max_length=12)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('mobile', models.CharField(blank=True, max_length=12)),
                ('gender', models.CharField(choices=[('ML', 'Male'), ('FM', 'Female'), ('NA', 'Not Available')], default='NA', max_length=2)),
                ('user_type', models.CharField(choices=[('ST', 'Staff'), ('DC', 'Department Coordinator'), ('TC', 'Training Coordinator'), ('AD', 'Administrator'), ('TR', 'Trainer')], default='ST', max_length=2)),
                ('grade', models.CharField(blank=True, max_length=100)),
                ('position', models.CharField(blank=True, max_length=100)),
                ('salary_code', models.CharField(blank=True, max_length=100)),
                ('department', models.CharField(choices=[('KA', 'Kawalan Bangunan'), ('KN', 'Kejuruteraan'), ('KK', 'Kesihatan, Persekitaraan dan Pelesenan'), ('PB', 'Perbendaharaan'), ('PP', 'Penilaian dan Pengurusan Harta'), ('UU', 'Undang-undang'), ('KP', 'Khidmat Pengurusan'), ('KM', 'Khidmat Kemasyarakatan'), ('KW', 'Konservasi Warisan'), ('PB', 'Pesuruhjaya Bangunan'), ('PG', 'Penguatkuasaan'), ('PN', 'Perkhidmatan Perbandaran'), ('LL', 'Landskap'), ('BP', 'Bahagian Pelesenan'), ('UD', 'Unit Audit Dalaman'), ('UO', 'Unit OSC'), ('NA', 'Not Available')], default='OT', max_length=2)),
                ('marital_type', models.CharField(choices=[('BW', 'Berkahwin'), ('BJ', 'Bujang'), ('NA', 'Not Available')], default='NA', max_length=2)),
                ('religion', models.CharField(choices=[('IM', 'Islam'), ('BA', 'Buddha'), ('HN', 'Hindu'), ('KN', 'Kristian'), ('NA', 'Not Available')], default='NA', max_length=2)),
                ('race', models.CharField(choices=[('MU', 'Melayu'), ('ID', 'India'), ('CN', 'Cina'), ('NA', 'Not Available')], default='OT', max_length=2)),
                ('profile_picture', models.TextField(max_length=100, null=True)),
                ('is_first_login', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organisations.Organisation')),
            ],
            options={
                'verbose_name': 'historical custom user',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
