# Generated by Django 2.2.6 on 2020-07-02 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.CharField(choices=[('PDB', 'Pejabat Datuk Bandar'), ('UUU', 'Unit Undang-undang'), ('UAD', 'Unit Audit Dalam'), ('UPP', 'Unit Penyelarasan Pembangunan'), ('UPS', 'Unit Pusat Sehenti'), ('JKP', 'Jabatan Khidmat Pengurusan'), ('JKD', 'Jabatan Perbendaharaan'), ('JPH', 'Jabatan Penilaian Pengurusan Harta'), ('JPP', 'Jabatan Perancangan Pembangunan'), ('JKJ', 'Jabatan Kejuruteraan'), ('JKB', 'Jabatan Kawalan Bangunan'), ('JKEA', 'Bahagian Kesihatan Awam'), ('JKEB', 'Bahagian Pelesenan'), ('JPR', 'Jabatan Perkhidmatan Perbandaraan'), ('JKK', 'Jabatan Khidmat Kemasyarakatan'), ('JKW', 'Jabatan Konservasi Warisan'), ('JKL', 'Jabatan Lanskap'), ('JPU', 'Jabatan Penguatkuasaan'), ('JPB', 'Jabatan Pesuruhjaya Bangunan'), ('NA', 'Not Available')], default='NA', max_length=4),
        ),
        migrations.AlterField(
            model_name='historicalcustomuser',
            name='department',
            field=models.CharField(choices=[('PDB', 'Pejabat Datuk Bandar'), ('UUU', 'Unit Undang-undang'), ('UAD', 'Unit Audit Dalam'), ('UPP', 'Unit Penyelarasan Pembangunan'), ('UPS', 'Unit Pusat Sehenti'), ('JKP', 'Jabatan Khidmat Pengurusan'), ('JKD', 'Jabatan Perbendaharaan'), ('JPH', 'Jabatan Penilaian Pengurusan Harta'), ('JPP', 'Jabatan Perancangan Pembangunan'), ('JKJ', 'Jabatan Kejuruteraan'), ('JKB', 'Jabatan Kawalan Bangunan'), ('JKEA', 'Bahagian Kesihatan Awam'), ('JKEB', 'Bahagian Pelesenan'), ('JPR', 'Jabatan Perkhidmatan Perbandaraan'), ('JKK', 'Jabatan Khidmat Kemasyarakatan'), ('JKW', 'Jabatan Konservasi Warisan'), ('JKL', 'Jabatan Lanskap'), ('JPU', 'Jabatan Penguatkuasaan'), ('JPB', 'Jabatan Pesuruhjaya Bangunan'), ('NA', 'Not Available')], default='NA', max_length=4),
        ),
    ]
