# Generated by Django 2.2.6 on 2020-09-12 03:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200702_0930'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['question'],
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='appointed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='department_code',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='customuser',
            name='grade_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='service_status',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='customuser',
            name='unit_code',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='historicalcustomuser',
            name='appointed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcustomuser',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcustomuser',
            name='department_code',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='historicalcustomuser',
            name='grade_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='historicalcustomuser',
            name='service_status',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='historicalcustomuser',
            name='unit_code',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.CreateModel(
            name='SecurityAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('answer', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.SecurityQuestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['question'],
            },
        ),
    ]
