# Generated by Django 2.2.6 on 2021-01-24 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210124_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='historicalcustomuser',
            name='grade',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='appointed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='confirmed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalcustomuser',
            name='appointed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalcustomuser',
            name='confirmed_at',
            field=models.DateTimeField(null=True),
        ),
    ]
