# Generated by Django 2.2.6 on 2021-02-17 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210209_0459'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['full_name']},
        ),
    ]
