# Generated by Django 2.2.6 on 2021-03-22 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0002_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalevaluation',
            name='answer_7',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='externalevaluation',
            name='answer_8',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='internalevaluation',
            name='answer_7',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='internalevaluation',
            name='answer_8',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='externalevaluation',
            name='answer_1',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='externalevaluation',
            name='answer_2',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='externalevaluation',
            name='answer_3',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='externalevaluation',
            name='answer_4',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='externalevaluation',
            name='answer_5',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='externalevaluation',
            name='answer_6',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='internalevaluation',
            name='answer_1',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='internalevaluation',
            name='answer_2',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='internalevaluation',
            name='answer_3',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='internalevaluation',
            name='answer_4',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='internalevaluation',
            name='answer_5',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='internalevaluation',
            name='answer_6',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
