# Generated by Django 2.2.6 on 2021-08-02 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0003_auto_20210322_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalevaluation',
            name='answer_9',
            field=models.TextField(null=True),
        ),
    ]
