# Generated by Django 2.2.6 on 2021-08-26 08:05

import core.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0005_externalevaluation_answer_9'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='cert',
            field=models.FileField(max_length=255, null=True, upload_to=core.helpers.PathAndRename('mbpp-elatihan/certificates')),
        ),
    ]
