# Generated by Django 2.2.6 on 2021-08-27 02:50

import core.helpers
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evaluations', '0006_auto_20210826_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalevaluation',
            name='evaluation',
            field=models.FileField(max_length=255, null=True, upload_to=core.helpers.PathAndRename('mbpp-elatihan/evaluations/external')),
        ),
        migrations.AddField(
            model_name='externalevaluation',
            name='generated_by',
            field=models.ForeignKey(limit_choices_to={'user_type': 'TC'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ex_evaluation_generated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='internalevaluation',
            name='evaluation',
            field=models.FileField(max_length=255, null=True, upload_to=core.helpers.PathAndRename('mbpp-elatihan/evaluations/internal')),
        ),
        migrations.AddField(
            model_name='internalevaluation',
            name='generated_by',
            field=models.ForeignKey(limit_choices_to={'user_type': 'TC'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='in_evaluation_generated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
