# Generated by Django 2.0.5 on 2019-12-05 06:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(default='NA', max_length=100)),
                ('exam_code', models.CharField(default='NA', max_length=100)),
                ('max_participant', models.IntegerField(default=0)),
                ('venue', models.CharField(default='NA', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ExamAbsence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('staff_id', models.CharField(default='NA', max_length=10)),
                ('exam_code', models.CharField(default='NA', max_length=10)),
                ('date_submitted', models.DateTimeField(null=True)),
                ('reason', models.CharField(default='NA', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ExamApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('exam_code', models.CharField(default='NA', max_length=100)),
                ('applicant_staff_id', models.CharField(default='NA', max_length=100)),
                ('current_position_appoint_date', models.DateTimeField(null=True)),
                ('current_position_promotion_date', models.DateTimeField(null=True)),
                ('current_appoint_type', models.CharField(choices=[('LT', 'Lantikan Terus'), ('KP', 'Kenaikan Pangkat Secara Latihan'), ('OT', 'Lain-Lain')], default='OT', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='ExamAttendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('check_in', models.DateTimeField(null=True)),
                ('check_out', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('exam_code', models.CharField(default='NA', max_length=10)),
                ('staff_id', models.CharField(default='NA', max_length=10)),
                ('result', models.CharField(default='NA', max_length=10)),
                ('date', models.DateTimeField(null=True)),
            ],
        ),
    ]
