# Generated by Django 2.0.5 on 2019-12-05 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattendance',
            name='attendee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_attendee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examattendance',
            name='exam_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exams.Exam'),
        ),
        migrations.AddField(
            model_name='examattendance',
            name='verified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_verified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examabsence',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='absence_approved_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exam',
            name='certify_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certify_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
