# Generated by Django 2.0.5 on 2019-12-05 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_auto_20191205_0622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='certify_by',
        ),
        migrations.AddField(
            model_name='exam',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
