# Generated by Django 2.0.5 on 2020-02-24 16:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_examevent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='examabsence',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='examapplication',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='examevent',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='examresult',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='examabsence',
            name='date_submitted',
        ),
        migrations.RemoveField(
            model_name='examevent',
            name='date_time',
        ),
        migrations.RemoveField(
            model_name='examresult',
            name='date',
        ),
        migrations.AddField(
            model_name='exam',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exam',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='examabsence',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examabsence',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='examapplication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examapplication',
            name='status_type',
            field=models.CharField(choices=[('PJ', 'Hantar Ke Penyelaras Jabatan'), ('PN', 'Hantar ke Pengarah Jabatan'), ('PL', 'Hantar Ke Penyelaras Latihan'), ('DD', 'Diterima'), ('TT', 'Ditolak'), ('NA', '-')], default='NA', max_length=2),
        ),
        migrations.AddField(
            model_name='examapplication',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='examevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
