# Generated by Django 2.2.6 on 2020-06-28 05:58

import core.helpers
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date', models.DateTimeField(blank=True)),
                ('document_copy', models.FileField(null=True, upload_to=core.helpers.PathAndRename('document'))),
                ('result', models.CharField(choices=[('PA', 'Pass'), ('FA', 'Failed'), ('NA', 'Not Available')], default='NA', max_length=2)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
