# Generated by Django 2.2.6 on 2020-07-01 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_exam_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='exam',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='exam',
            old_name='modified_date',
            new_name='modified_at',
        ),
    ]
