# Generated by Django 2.2.6 on 2020-07-02 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_auto_20200701_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='classification',
            field=models.CharField(choices=[('FKW', 'Faedah Kewangan'), ('PDP', 'Pengesahan Dalam Perkhidmatan'), ('PSL', 'Peperiksaan Peningkatan Secara Lantikan (PSL)'), ('NA', 'Not Available')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='exam',
            name='note',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
