# Generated by Django 2.2.6 on 2021-01-27 10:15

import core.helpers
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0004_auto_20200702_0301'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamAttendee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(blank=True)),
                ('document_copy', models.FileField(null=True, upload_to=core.helpers.PathAndRename('document'))),
                ('result', models.CharField(choices=[('PA', 'Pass'), ('FA', 'Failed'), ('NA', 'Not Available')], default='NA', max_length=2)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_staff', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Exam',
        ),
    ]
