# Generated by Django 2.2.6 on 2021-01-28 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_auto_20210127_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
