# Generated by Django 2.2.6 on 2021-02-27 07:38

import core.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_auto_20210128_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examattendee',
            name='document_copy',
            field=models.FileField(null=True, upload_to=core.helpers.PathAndRename('mbpp-elatihan/documents')),
        ),
    ]
