# Generated by Django 2.0.5 on 2019-12-05 06:22

from django.db import migrations, models
import mbpp_tms_api.helpers
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('course_code', models.CharField(default='NA', max_length=10)),
                ('title', models.CharField(default='NA', max_length=100)),
                ('description', models.CharField(default='NA', max_length=100)),
                ('training_type', models.CharField(choices=[('LL', 'Luaran'), ('DD', 'Dalaman'), ('OT', 'Lain-Lain')], default='OT', max_length=2)),
                ('course_type', models.CharField(choices=[('KK', 'Kursus'), ('PP', 'Persidangan'), ('SS', 'Seminar'), ('BB', 'Bengkel'), ('LK', 'Lawatan Kerja'), ('TT', 'Taklimat'), ('SP', 'Sesi Perjumpaan'), ('OT', 'Lain-Lain')], default='OT', max_length=2)),
                ('target_group', models.CharField(default='NA', max_length=20, null=True)),
                ('department_type', models.CharField(choices=[('KW', 'KAWALAN BANGUNAN'), ('KN', 'KEJURUTERAAN'), ('KK', 'KESIHATAN,PERSEKITARAAN DAN PELESENAN'), ('PB', 'PERBENDAHARAAN'), ('PP', 'PENILAIAN DAN PENGURUSAN HARTA'), ('UU', 'UNDANG-UNDANG'), ('KP', 'KHIDMAT PENGURUSAN'), ('KM', 'KHIDMAT KEMASYARAKATAN'), ('KW', 'KONSERVASI WARISAN'), ('PB', 'PESURUHJAYA BANGUNAN'), ('PG', 'PENGUATKUASAAAN'), ('PN', 'PERKHIDMATAN PERBANDARAN'), ('LL', 'LANDSKAP'), ('BP', 'BAHAGIAN PELESENAN'), ('UD', 'UNIT AUDIT DALAMAN'), ('UO', 'UNIT OSC'), ('OT', 'Other')], default='OT', max_length=2)),
                ('organiser', models.CharField(default='NA', max_length=50, null=True)),
                ('max_participant', models.IntegerField(default=0)),
                ('venue', models.CharField(default='NA', max_length=50, null=True)),
                ('address', models.CharField(default='NA', max_length=50, null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('start_time', models.TimeField(null=True)),
                ('end_time', models.TimeField(null=True)),
                ('cost', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('course_code', models.CharField(default='NA', max_length=10)),
                ('date_applied', models.DateTimeField(null=True)),
                ('status_type', models.CharField(choices=[('PJ', 'Hantar Ke Penyelaras Jabatan'), ('PN', 'Hantar ke Pengarah Jabatan'), ('PL', 'Hantar Ke Penyelaras Latihan'), ('DD', 'Diterima'), ('TT', 'Ditolak'), ('NA', '-')], default='-', max_length=2)),
                ('comment', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingAssessmentAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('answer', models.CharField(default='NA', max_length=100)),
                ('date_answered', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingAssessmentQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('assessment_question', models.CharField(default='NA', max_length=100)),
                ('assessment_type', models.CharField(default='NA', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingAttendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('check_in', models.DateTimeField(null=True)),
                ('check_out', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingNeedAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('question_id', models.CharField(default='NA', max_length=100)),
                ('date_answered', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingNeedQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('question', models.CharField(default='NA', max_length=100)),
                ('question_type', models.CharField(default='NA', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('course_code', models.CharField(default='NA', max_length=10)),
                ('title', models.CharField(default='NA', max_length=10)),
                ('note_code', models.CharField(default='NA', max_length=10)),
                ('note_file', models.ImageField(null=True, upload_to=mbpp_tms_api.helpers.PathAndRename('notes'))),
            ],
        ),
    ]
