# Generated by Django 2.0.5 on 2019-12-05 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trainings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingneedanswer',
            name='answered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingattendance',
            name='attendee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_attendee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingattendance',
            name='training',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trainings.Training'),
        ),
        migrations.AddField(
            model_name='trainingattendance',
            name='verified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_verified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingassessmentanswer',
            name='answered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingapplication',
            name='applicant_staff_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_staff_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingapplication',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_approved_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingapplication',
            name='department_coordinator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_department_coordinator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='training',
            name='fasilitator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fasilitator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='training',
            name='speaker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='speaker', to=settings.AUTH_USER_MODEL),
        ),
    ]
