# Generated by Django 2.0.5 on 2019-12-12 01:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trainings', '0002_auto_20191205_0622'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingAbsent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('staff_id', models.CharField(default='NA', max_length=10)),
                ('exam_code', models.CharField(default='NA', max_length=10)),
                ('date_submitted', models.DateTimeField(null=True)),
                ('reason', models.CharField(default='NA', max_length=10)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainingabsent_approved_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
