# Generated by Django 2.0.5 on 2020-01-20 08:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trainings', '0003_trainingabsent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TrainingAbsent',
            new_name='TrainingAbsence',
        ),
    ]
