# Generated by Django 2.0.5 on 2020-01-21 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0004_auto_20200120_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingabsence',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainingabsence_approved_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
