# Generated by Django 2.0.5 on 2020-01-22 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0005_auto_20200121_0715'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='training',
            name='status_type',
            field=models.CharField(choices=[('DB', 'DIBUKA'), ('DT', 'DITUTUP'), ('PN', 'PENUH'), ('TN', 'TANGGUH'), ('OT', 'LAIN-LAIN')], default='OT', max_length=2),
        ),
    ]
