# Generated by Django 2.0.5 on 2020-01-23 02:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0006_auto_20200122_0722'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('course_type', models.CharField(default='NA', max_length=50, null=True)),
                ('code', models.CharField(default='NA', max_length=20, null=True)),
            ],
        ),
    ]
