# Generated by Django 2.0.5 on 2020-01-23 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0007_trainingcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainingcode',
            old_name='course_type',
            new_name='course_code',
        ),
    ]
