# Generated by Django 2.0.5 on 2020-01-24 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0010_trainingevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingassessmentanswer',
            name='assessment_type',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
