# Generated by Django 2.0.5 on 2020-01-24 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0011_trainingassessmentanswer_assessment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='course_code',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
