# Generated by Django 2.0.5 on 2020-02-24 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0012_auto_20200124_0459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='department_type',
            field=models.CharField(choices=[('KA', 'KAWALAN BANGUNAN'), ('KN', 'KEJURUTERAAN'), ('KK', 'KESIHATAN,PERSEKITARAAN DAN PELESENAN'), ('PB', 'PERBENDAHARAAN'), ('PP', 'PENILAIAN DAN PENGURUSAN HARTA'), ('UU', 'UNDANG-UNDANG'), ('KP', 'KHIDMAT PENGURUSAN'), ('KM', 'KHIDMAT KEMASYARAKATAN'), ('KW', 'KONSERVASI WARISAN'), ('PB', 'PESURUHJAYA BANGUNAN'), ('PG', 'PENGUATKUASAAAN'), ('PN', 'PERKHIDMATAN PERBANDARAN'), ('LL', 'LANDSKAP'), ('BP', 'BAHAGIAN PELESENAN'), ('UD', 'UNIT AUDIT DALAMAN'), ('UO', 'UNIT OSC'), ('OT', 'Other')], default='OT', max_length=2),
        ),
    ]
