# Generated by Django 2.0.5 on 2020-02-24 16:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0013_auto_20200224_0317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='training',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='trainingabsence',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='trainingapplication',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='trainingassessmentanswer',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='trainingassessmentquestion',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='trainingcode',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='trainingevent',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='trainingneedanswer',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='trainingneedquestion',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='trainingnote',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='trainingabsence',
            name='date_submitted',
        ),
        migrations.RemoveField(
            model_name='trainingapplication',
            name='date_applied',
        ),
        migrations.RemoveField(
            model_name='trainingassessmentanswer',
            name='date_answered',
        ),
        migrations.RemoveField(
            model_name='trainingevent',
            name='date_time',
        ),
        migrations.RemoveField(
            model_name='trainingneedanswer',
            name='date_answered',
        ),
        migrations.AddField(
            model_name='training',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='training',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='trainingabsence',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainingapplication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainingapplication',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='trainingassessmentanswer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainingassessmentquestion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainingassessmentquestion',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='trainingcode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainingcode',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='trainingevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainingevent',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='trainingneedanswer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainingneedquestion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainingneedquestion',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='trainingnote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainingnote',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='department_type',
            field=models.CharField(choices=[('KA', 'Kawalan Bangunan'), ('KN', 'Kejuruteraan'), ('KK', 'Kesihatan, Persekitaraan dan Pelesenan'), ('PB', 'Perbendaharaan'), ('PP', 'Penilaian dan Pengurusan Harta'), ('UU', 'Undang-undang'), ('KP', 'Khidmat Pengurusan'), ('KM', 'Khidmat Kemasyarakatan'), ('KW', 'Konservasi Warisan'), ('PB', 'Pesuruhjaya Bangunan'), ('PG', 'Penguatkuasaan'), ('PN', 'Perkhidmatan Perbandaran'), ('LL', 'Landskap'), ('BP', 'Bahagian Pelesenan'), ('UD', 'Unit Audit Dalaman'), ('UO', 'Unit OSC'), ('OT', 'Other')], default='OT', max_length=2),
        ),
        migrations.AlterField(
            model_name='training',
            name='status_type',
            field=models.CharField(choices=[('DB', 'Dibuka'), ('DT', 'Ditutup'), ('PN', 'Penuh'), ('TN', 'Tangguh'), ('OT', 'Lain-lain')], default='OT', max_length=2),
        ),
        migrations.AlterField(
            model_name='trainingapplication',
            name='status_type',
            field=models.CharField(choices=[('PJ', 'Hantar Ke Penyelaras Jabatan'), ('PN', 'Hantar ke Pengarah Jabatan'), ('PL', 'Hantar Ke Penyelaras Latihan'), ('DD', 'Diterima'), ('TT', 'Ditolak'), ('NA', '-')], default='NA', max_length=2),
        ),
    ]
