# Generated by Django 2.0.5 on 2020-02-24 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0014_auto_20200224_1641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainingabsence',
            old_name='exam_code',
            new_name='course_code',
        ),
        migrations.AddField(
            model_name='trainingabsence',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
