# Generated by Django 2.0.5 on 2020-02-28 06:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0015_auto_20200224_2322'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingCodeCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('category_name', models.CharField(default='NA', max_length=100)),
                ('category_code', models.CharField(default='NA', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingCodeClass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('class_name', models.CharField(default='NA', max_length=100)),
                ('class_code', models.CharField(default='NA', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingCodeGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('group_name', models.CharField(default='NA', max_length=100)),
                ('group_code', models.CharField(default='NA', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='trainingcodeclass',
            name='group_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_id', to='trainings.TrainingCodeGroup'),
        ),
        migrations.AddField(
            model_name='trainingcodecategory',
            name='class_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_id', to='trainings.TrainingCodeClass'),
        ),
    ]
