# Generated by Django 2.0.5 on 2020-02-28 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0016_auto_20200228_0648'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainingcodecategory',
            options={'ordering': ['category_code']},
        ),
        migrations.AlterModelOptions(
            name='trainingcodeclass',
            options={'ordering': ['class_code']},
        ),
        migrations.AlterModelOptions(
            name='trainingcodegroup',
            options={'ordering': ['group_code']},
        ),
    ]
