# Generated by Django 2.0.5 on 2020-02-28 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0003_remove_organisation_client_type'),
        ('trainings', '0017_auto_20200228_0734'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='agency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency', to='organisations.Organisation'),
        ),
    ]
