# Generated by Django 2.0.5 on 2020-03-01 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0018_training_agency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='training',
            old_name='training_type',
            new_name='organiser_type',
        ),
        migrations.AddField(
            model_name='training',
            name='category',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='training',
            name='target_group_type',
            field=models.CharField(choices=[('TB', 'Terbuka'), ('TH', 'Terhad')], default='TB', max_length=2),
        ),
        migrations.AlterField(
            model_name='training',
            name='target_group',
            field=models.CharField(choices=[('GD', 'Gred'), ('JB', 'Jabatan'), ('JW', 'Jawatan'), ('SM', 'Semua'), ('SP', 'Skim Perkhidmatan')], default='SM', max_length=2),
        ),
    ]
