# Generated by Django 2.0.5 on 2020-03-01 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0019_auto_20200301_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='agency',
            field=models.CharField(default='NA', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='fasilitator',
            field=models.CharField(default='NA', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='speaker',
            field=models.CharField(default='NA', max_length=100, null=True),
        ),
    ]
