# Generated by Django 2.0.5 on 2019-12-05 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191205_0631'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='marital_type',
            field=models.CharField(choices=[('BW', 'BERKAHWIN'), ('BJ', 'BUJANG'), ('OT', 'Other')], default='OT', max_length=2),
        ),
    ]
