# Generated by Django 2.0.5 on 2019-12-05 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_marital_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='race_type',
            field=models.CharField(choices=[('MU', 'MELAYU'), ('ND', 'INDIA'), ('CN', 'CINA'), ('OT', 'Other')], default='OT', max_length=2),
        ),
        migrations.AddField(
            model_name='customuser',
            name='religion_type',
            field=models.CharField(choices=[('IM', 'ISLAM'), ('BA', 'BUDDHA'), ('HN', 'HINDU'), ('KN', 'KRISTIAN'), ('OT', 'Other')], default='OT', max_length=2),
        ),
    ]
