# Generated by Django 2.0.5 on 2020-01-21 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20191206_0622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='gred',
            new_name='grade',
        ),
    ]
