# Generated by Django 2.0.5 on 2020-02-24 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200123_0311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender_type',
            field=models.CharField(choices=[('ML', 'Male'), ('FM', 'Female'), ('OT', 'Other')], default='OT', max_length=2),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='race_type',
            field=models.CharField(choices=[('MU', 'MELAYU'), ('ID', 'INDIA'), ('CN', 'CINA'), ('OT', 'Other')], default='OT', max_length=2),
        ),
    ]
