# Generated by Django 2.0.5 on 2020-02-24 16:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200224_0325'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-full_name']},
        ),
        migrations.AlterModelOptions(
            name='userevent',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='userevent',
            name='date_time',
        ),
        migrations.AddField(
            model_name='userevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='department_type',
            field=models.CharField(choices=[('KA', 'Kawalan Bangunan'), ('KN', 'Kejuruteraan'), ('KK', 'Kesihatan, Persekitaraan dan Pelesenan'), ('PB', 'Perbendaharaan'), ('PP', 'Penilaian dan Pengurusan Harta'), ('UU', 'Undang-undang'), ('KP', 'Khidmat Pengurusan'), ('KM', 'Khidmat Kemasyarakatan'), ('KW', 'Konservasi Warisan'), ('PB', 'Pesuruhjaya Bangunan'), ('PG', 'Penguatkuasaan'), ('PN', 'Perkhidmatan Perbandaran'), ('LL', 'Landskap'), ('BP', 'Bahagian Pelesenan'), ('UD', 'Unit Audit Dalaman'), ('UO', 'Unit OSC'), ('OT', 'Other')], default='OT', max_length=2),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='marital_type',
            field=models.CharField(choices=[('BW', 'Berkahwin'), ('BJ', 'Bujang'), ('OT', 'Other')], default='OT', max_length=2),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='race_type',
            field=models.CharField(choices=[('MU', 'Melayu'), ('ID', 'India'), ('CN', 'Cina'), ('OT', 'Other')], default='OT', max_length=2),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='religion_type',
            field=models.CharField(choices=[('IM', 'Islam'), ('BA', 'Buddha'), ('HN', 'Hindu'), ('KN', 'Kristian'), ('OT', 'Other')], default='OT', max_length=2),
        ),
    ]
