# Generated by Django 2.0.5 on 2020-03-10 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200224_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_first_time',
            field=models.BooleanField(default=True),
        ),
    ]
