# Generated by Django 2.0.5 on 2020-03-10 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_customuser_is_first_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('ST', 'Staff'), ('DC', 'Department Coordinator'), ('DH', 'Department Head'), ('DD', 'Department Director'), ('TC', 'Training Coordinator'), ('AD', 'Administrator'), ('TR', 'Trainer'), ('OT', 'Other')], default='OT', max_length=2),
        ),
    ]
