# Generated by Django 2.0.5 on 2020-03-10 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_securityquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='staff_id',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
