# Generated by Django 2.0.5 on 2020-03-10 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_customuser_staff_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_first_time',
            new_name='is_first_login',
        ),
    ]
