# Generated by Django 2.0.5 on 2020-03-11 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20200310_0351'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='salary_code',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
